docker-build:
  image: docker:stable
  stage: build
  tags:
    - app
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - |
      if [$CI_COMMIT_TAG == '']
      then
        tag="latest"
      else 
        tag="$CI_COMMIT_TAG"
      fi
    - sed -i 's/app_version =.*/app_version = "${CI_COMMIT_TAG}"/' index.php
    - docker build --pull -t "$CI_REGISTRY_IMAGE:${CI_COMMIT_TAG}" -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE:${CI_COMMIT_TAG}"
