build:
  image: docker:stable
  stage: build
  tags:
    - app
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - |
      if [[ $CI_COMMIT_TAG == '' && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH ]]; then
        TAG="latest"
      elif [[ $CI_COMMIT_TAG == '' && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH ]]; then
        TAG="$CI_COMMIT_BRANCH_$CI_COMMIT_SHORT_SHA"
      fi
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$TAG" -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE:$TAG"


# deploy:
#   image: 
#     name: bitnami/kubectl:latest
#     entrypoint: [""]
#   stage: deploy

#   script:
#     - |
#       if [$CI_COMMIT_TAG == '']
#       then
#         tag="$CI_COMMIT_SHORT_SHA"
#       else 
#        tag="$CI_COMMIT_TAG"
#       fi
#     - kubectl config set-cluster k8s --server="$KUBE_URL" --insecure-skip-tls-verify=true
#     - kubectl config set-credentials admin --token="$KUBE_TOKEN"
#     - kubectl config set-context default --cluster=k8s --user=admin
#     - kubectl config use-context default
#     - sed -i "s/__VERSION__/$tag/" k8s.yaml
#     - sed -i "s/__REGISTRY__/$REGISTRYID/" k8s.yaml
#     - kubectl apply -f k8s.yaml
#   rules:
#     - if: $CI_COMMIT_TAG
